const response = {
  jsonrpc: '2.0',
  authenticated: false,
  result: {
    results: [
      {
        resource: {
          id: 7,
          registrationPlate: 'AA-CD-05',
          alias: 'owner wheels 5',
          resourceType: 'car',
          brand: null,
          model: null,
          color: null,
          fuelType: null,
          numberOfSeats: 4,
          location: 'Van Limburg Brouwerstraat',
          streetNumber: null,
          latitude: 52.090793,
          longitude: 5.111107,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Utrecht',
          locktype: 'meeting',
          parkingType: 'default',
          fuelLevel: null,
          fuelRange: null,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 0,
          chargeAdapterConnectedSince: null,
          price: {
            id: 7,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 7,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['meeting'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 16,
          registrationPlate: 'SK-OD-01',
          alias: 'skoda-citigo-active-micpoint',
          resourceType: 'car',
          brand: 'Skoda',
          model: 'Citigo',
          color: null,
          fuelType: 'benzine',
          numberOfSeats: 4,
          location: 'Barkastraat',
          streetNumber: null,
          latitude: 52.090793,
          longitude: 5.111107,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Utrecht',
          locktype: 'meeting',
          parkingType: 'parking_spot',
          fuelLevel: null,
          fuelRange: null,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 200,
          chargeAdapterConnectedSince: null,
          price: {
            id: 16,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 16,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['meeting'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 53,
          registrationPlate: 'EN-01-01',
          alias: 'Renault MEGANE Zen Stationsplein',
          resourceType: 'Gezinsauto',
          brand: 'Renault',
          model: 'MEGANE Zen',
          color: 'Blauw',
          fuelType: 'elektrisch',
          numberOfSeats: 4,
          location: 'Stationsplein',
          streetNumber: '1',
          latitude: 52.699888,
          longitude: 5.288254,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Enkhuizen',
          locktype: 'chipcard',
          parkingType: 'parking_spot',
          fuelLevel: 100,
          fuelRange: 900,
          charging: false,
          chargeAdapterConnected: true,
          fuelRangeDefault: 0,
          chargeAdapterConnectedSince: '2023-05-08 10:35',
          price: {
            id: 53,
            hourRate: '3.50',
            kilometerRate: '0.27',
            fuelPerKilometer: '0.00',
            dayRateTotal: '35.00',
          },
          options: {
            id: 53,
            automatic: false,
            winterTires: false,
            towbar: true,
          },
          locktypes: ['chipcard'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 59,
          registrationPlate: 'TE-ST-02',
          alias: 'Kia e-Niro KNSM Eiland (test success connection)',
          resourceType: 'Elektrische auto',
          brand: 'Kia',
          model: 'e-Niro',
          color: 'wit',
          fuelType: 'elektrisch',
          numberOfSeats: 4,
          location: 'KNSM Eiland (test success connection)',
          streetNumber: '1',
          latitude: 52.377191,
          longitude: 4.948425,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Amsterdam',
          locktype: 'chipcard',
          parkingType: 'parking_spot',
          fuelLevel: 100,
          fuelRange: 400,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 400,
          chargeAdapterConnectedSince: null,
          price: {
            id: 59,
            hourRate: '4.25',
            kilometerRate: '0.36',
            fuelPerKilometer: '0.00',
            dayRateTotal: '42.50',
          },
          options: { id: 59, automatic: true, winterTires: true, towbar: true },
          locktypes: ['chipcard'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 45,
          registrationPlate: 'XR-432-G',
          alias: 'Hely Citroen C1',
          resourceType: 'car',
          brand: 'Citroen',
          model: 'C1-5 Feel',
          color: 'blauw',
          fuelType: 'benzine',
          numberOfSeats: 4,
          location: 'Antonio Vivaldistraat',
          streetNumber: '103',
          latitude: 52.336214347229,
          longitude: 4.8844302100346,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Amsterdam',
          locktype: 'smartphone',
          parkingType: 'default',
          fuelLevel: null,
          fuelRange: null,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 600,
          chargeAdapterConnectedSince: null,
          price: {
            id: 45,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 45,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['smartphone'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 20,
          registrationPlate: 'SK-OD-05',
          alias: 'skoda-citigo-space-micpoint',
          resourceType: 'car',
          brand: 'Skoda',
          model: 'Citigo',
          color: null,
          fuelType: null,
          numberOfSeats: 4,
          location: 'Tractieweg',
          streetNumber: null,
          latitude: 52.090793,
          longitude: 5.111107,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Utrecht',
          locktype: 'meeting',
          parkingType: 'default',
          fuelLevel: null,
          fuelRange: null,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 200,
          chargeAdapterConnectedSince: null,
          price: {
            id: 20,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 20,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['meeting'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 26,
          registrationPlate: 'TV-123-S',
          alias: 'Nissan Leaf Schoemakerplantage',
          resourceType: 'car',
          brand: 'Nissan',
          model: 'Leaf',
          color: 'wit',
          fuelType: 'elektrisch',
          numberOfSeats: 4,
          location: 'Antonio Vivaldistraat',
          streetNumber: '103',
          latitude: 52.336214347229,
          longitude: 4.8844302100346,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Amsterdam',
          locktype: 'smartphone',
          parkingType: 'default',
          fuelLevel: null,
          fuelRange: null,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 200,
          chargeAdapterConnectedSince: null,
          price: {
            id: 26,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 26,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['smartphone'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 19,
          registrationPlate: 'SK-OD-04',
          alias: 'skoda-citigo-sport-micpoint',
          resourceType: 'car',
          brand: 'Skoda',
          model: 'Citigo',
          color: null,
          fuelType: null,
          numberOfSeats: 4,
          location: 'Nijverheidsweg',
          streetNumber: null,
          latitude: 52.090793,
          longitude: 5.111107,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Utrecht',
          locktype: 'meeting',
          parkingType: 'default',
          fuelLevel: null,
          fuelRange: null,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 200,
          chargeAdapterConnectedSince: null,
          price: {
            id: 19,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 19,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['meeting'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 37,
          registrationPlate: 'XR-424-G',
          alias: 'Hely Citroen C1',
          resourceType: 'car',
          brand: 'Citroen',
          model: 'C1-5 Feel',
          color: 'blauw',
          fuelType: 'benzine',
          numberOfSeats: 4,
          location: 'Antonio Vivaldistraat',
          streetNumber: '103',
          latitude: 52.336214347229,
          longitude: 4.8844302100346,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Amsterdam',
          locktype: 'smartphone',
          parkingType: 'default',
          fuelLevel: null,
          fuelRange: null,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 600,
          chargeAdapterConnectedSince: null,
          price: {
            id: 37,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 37,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['smartphone'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 9,
          registrationPlate: 'AA-CD-06',
          alias: 'owner wheels go',
          resourceType: 'car',
          brand: null,
          model: null,
          color: null,
          fuelType: null,
          numberOfSeats: 4,
          location: 'Straingstraat',
          streetNumber: null,
          latitude: 52.090793,
          longitude: 5.111107,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Utrecht',
          locktype: 'meeting',
          parkingType: 'default',
          fuelLevel: null,
          fuelRange: null,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 0,
          chargeAdapterConnectedSince: null,
          price: {
            id: 9,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 9,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['meeting'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 10,
          registrationPlate: 'AA-CD-07',
          alias: 'owner wheels go 2',
          resourceType: 'car',
          brand: null,
          model: null,
          color: null,
          fuelType: null,
          numberOfSeats: 4,
          location: 'Johan de Meesterstraat',
          streetNumber: null,
          latitude: 52.090793,
          longitude: 5.111107,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Utrecht',
          locktype: 'meeting',
          parkingType: 'default',
          fuelLevel: null,
          fuelRange: null,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 0,
          chargeAdapterConnectedSince: null,
          price: {
            id: 10,
            hourRate: '0.01',
            kilometerRate: '0.00',
            fuelPerKilometer: '0.00',
            dayRateTotal: '5.00',
          },
          options: {
            id: 10,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['meeting'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 48,
          registrationPlate: 'NI-SS-11',
          alias: 'Nissan Evalia TEST',
          resourceType: 'car',
          brand: 'Nissan',
          model: 'Evalia',
          color: 'Groen',
          fuelType: 'elektrisch',
          numberOfSeats: 4,
          location: 'Bessemerlaan',
          streetNumber: null,
          latitude: 52.090793,
          longitude: 5.111107,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Utrecht',
          locktype: 'smartphone',
          parkingType: 'default',
          fuelLevel: 15,
          fuelRange: 95,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 0,
          chargeAdapterConnectedSince: null,
          price: {
            id: 48,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 48,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['smartphone'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 13,
          registrationPlate: 'AA-CD-11',
          alias: 'ronald-test-owner',
          resourceType: 'car',
          brand: null,
          model: null,
          color: null,
          fuelType: null,
          numberOfSeats: 4,
          location: null,
          streetNumber: null,
          latitude: 52.090793,
          longitude: 5.111107,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: null,
          locktype: 'meeting',
          parkingType: 'default',
          fuelLevel: null,
          fuelRange: null,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 0,
          chargeAdapterConnectedSince: null,
          price: {
            id: 13,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 13,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['meeting'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 56,
          registrationPlate: 'OC-02-01',
          alias: 'Opel Corsa Hoorn Stationsplein',
          resourceType: 'Gezinsauto',
          brand: 'Opel',
          model: 'Corsa',
          color: 'Diamond Black',
          fuelType: 'benzine',
          numberOfSeats: 4,
          location: 'Hoorn Stationsplein',
          streetNumber: '1',
          latitude: 52.645008011504,
          longitude: 5.0538740783501,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Hoorn',
          locktype: 'chipcard',
          parkingType: 'default',
          fuelLevel: 74,
          fuelRange: 518,
          charging: false,
          chargeAdapterConnected: false,
          fuelRangeDefault: 700,
          chargeAdapterConnectedSince: null,
          price: {
            id: 56,
            hourRate: '3.50',
            kilometerRate: '0.27',
            fuelPerKilometer: '0.00',
            dayRateTotal: '35.00',
          },
          options: {
            id: 56,
            automatic: false,
            winterTires: false,
            towbar: true,
          },
          locktypes: ['chipcard'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 6,
          registrationPlate: 'AA-CD-04',
          alias: 'owner wheels 4',
          resourceType: 'car',
          brand: null,
          model: null,
          color: null,
          fuelType: null,
          numberOfSeats: 4,
          location: 'Vleutenseweg',
          streetNumber: null,
          latitude: 52.090793,
          longitude: 5.111107,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Utrecht',
          locktype: 'meeting',
          parkingType: 'default',
          fuelLevel: null,
          fuelRange: null,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 0,
          chargeAdapterConnectedSince: null,
          price: {
            id: 6,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 6,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['meeting'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 24,
          registrationPlate: 'TV-125-S',
          alias: 'Nissan Leaf Buiksloterham',
          resourceType: 'car',
          brand: 'Nissan',
          model: 'Leaf',
          color: 'wit',
          fuelType: 'elektrisch',
          numberOfSeats: 4,
          location: 'Antonio Vivaldistraat',
          streetNumber: '103',
          latitude: 52.336214347229,
          longitude: 4.8844302100346,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Amsterdam',
          locktype: 'smartphone',
          parkingType: 'default',
          fuelLevel: null,
          fuelRange: null,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 200,
          chargeAdapterConnectedSince: null,
          price: {
            id: 24,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 24,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['smartphone'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 28,
          registrationPlate: 'SH-156-N',
          alias: 'Hely Peugeot 108',
          resourceType: 'car',
          brand: 'Peugeot',
          model: '108',
          color: 'zwart',
          fuelType: 'benzine',
          numberOfSeats: 4,
          location: 'Antonio Vivaldistraat',
          streetNumber: '103',
          latitude: 52.336214347229,
          longitude: 4.8844302100346,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Amsterdam',
          locktype: 'smartphone',
          parkingType: 'default',
          fuelLevel: null,
          fuelRange: null,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 0,
          chargeAdapterConnectedSince: null,
          price: {
            id: 28,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 28,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['smartphone'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 18,
          registrationPlate: 'SK-OD-03',
          alias: 'skoda-citigo-style-micpoint',
          resourceType: 'car',
          brand: 'Skoda',
          model: 'Citigo',
          color: null,
          fuelType: null,
          numberOfSeats: 4,
          location: 'Industriehavenbrug',
          streetNumber: null,
          latitude: 52.090793,
          longitude: 5.111107,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Utrecht',
          locktype: 'meeting',
          parkingType: 'default',
          fuelLevel: null,
          fuelRange: null,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 200,
          chargeAdapterConnectedSince: null,
          price: {
            id: 18,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 18,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['meeting'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 25,
          registrationPlate: 'TV-126-S',
          alias: 'Nissan Leaf Buiksloterham',
          resourceType: 'car',
          brand: 'Nissan',
          model: 'Leaf',
          color: 'wit',
          fuelType: 'elektrisch',
          numberOfSeats: 4,
          location: 'Antonio Vivaldistraat',
          streetNumber: '103',
          latitude: 52.336214347229,
          longitude: 4.8844302100346,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Amsterdam',
          locktype: 'smartphone',
          parkingType: 'default',
          fuelLevel: null,
          fuelRange: null,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 200,
          chargeAdapterConnectedSince: null,
          price: {
            id: 25,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 25,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['smartphone'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 51,
          registrationPlate: 'GR-01-03',
          alias: 'Renault CAPTUR Intens Hoekstraat',
          resourceType: 'Gezinsauto',
          brand: 'Renault',
          model: 'CAPTUR Intens',
          color: 'Zwart',
          fuelType: 'benzine',
          numberOfSeats: 4,
          location: 'Hoekstraat',
          streetNumber: '1',
          latitude: 53.220231,
          longitude: 6.560815,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Groningen',
          locktype: 'chipcard',
          parkingType: 'default',
          fuelLevel: 15,
          fuelRange: 90,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 0,
          chargeAdapterConnectedSince: null,
          price: {
            id: 51,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 51,
            automatic: false,
            winterTires: false,
            towbar: true,
          },
          locktypes: ['chipcard'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 1,
          registrationPlate: 'AA-CD-01',
          alias: 'owner wheels',
          resourceType: 'car',
          brand: null,
          model: null,
          color: null,
          fuelType: null,
          numberOfSeats: 4,
          location: 'Ceramstraat',
          streetNumber: null,
          latitude: 52.090793,
          longitude: 5.111107,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Utrecht',
          locktype: 'meeting',
          parkingType: 'default',
          fuelLevel: null,
          fuelRange: null,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 0,
          chargeAdapterConnectedSince: null,
          price: {
            id: 1,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 1,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['meeting'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 40,
          registrationPlate: 'XR-427-G',
          alias: 'Hely Citroen C1',
          resourceType: 'car',
          brand: 'Citroen',
          model: 'C1-5 Feel',
          color: 'blauw',
          fuelType: 'benzine',
          numberOfSeats: 4,
          location: 'Antonio Vivaldistraat',
          streetNumber: '103',
          latitude: 52.336214347229,
          longitude: 4.8844302100346,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Amsterdam',
          locktype: 'smartphone',
          parkingType: 'default',
          fuelLevel: null,
          fuelRange: null,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 600,
          chargeAdapterConnectedSince: null,
          price: {
            id: 40,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 40,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['smartphone'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 32,
          registrationPlate: 'XR-420-G',
          alias: 'Hely Citroen C1',
          resourceType: 'car',
          brand: 'Citroen',
          model: 'C1-5 Feel',
          color: 'blauw',
          fuelType: 'benzine',
          numberOfSeats: 4,
          location: 'Antonio Vivaldistraat',
          streetNumber: '103',
          latitude: 52.336214347229,
          longitude: 4.8844302100346,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Amsterdam',
          locktype: 'smartphone',
          parkingType: 'default',
          fuelLevel: null,
          fuelRange: null,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 600,
          chargeAdapterConnectedSince: null,
          price: {
            id: 32,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 32,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['smartphone'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 30,
          registrationPlate: 'XR-421-G',
          alias: 'Hely Citroen C3',
          resourceType: 'car',
          brand: 'Citroen',
          model: 'C3 Feel',
          color: 'zwart',
          fuelType: 'benzine',
          numberOfSeats: 4,
          location: 'Antonio Vivaldistraat',
          streetNumber: '103',
          latitude: 52.336214347229,
          longitude: 4.8844302100346,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Amsterdam',
          locktype: 'smartphone',
          parkingType: 'default',
          fuelLevel: null,
          fuelRange: null,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 700,
          chargeAdapterConnectedSince: null,
          price: {
            id: 30,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 30,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['smartphone'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 47,
          registrationPlate: 'PA-RT-01',
          alias: 'mywheels partner auto 1',
          resourceType: 'car',
          brand: null,
          model: null,
          color: null,
          fuelType: null,
          numberOfSeats: 4,
          location: 'Marie Curielaan',
          streetNumber: null,
          latitude: 52.090793,
          longitude: 5.111107,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Utrecht',
          locktype: 'meeting',
          parkingType: 'default',
          fuelLevel: null,
          fuelRange: null,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 0,
          chargeAdapterConnectedSince: null,
          price: {
            id: 47,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 47,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['meeting'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 14,
          registrationPlate: 'VW-EG-88',
          alias: 'Elektrische-VW-eGolf',
          resourceType: 'car',
          brand: 'Volkswagen',
          model: 'Golf',
          color: null,
          fuelType: 'elektrisch',
          numberOfSeats: 4,
          location: 'Galjoenstraat',
          streetNumber: null,
          latitude: 52.090793,
          longitude: 5.111107,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Utrecht',
          locktype: 'meeting',
          parkingType: 'default',
          fuelLevel: 15,
          fuelRange: 90,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 0,
          chargeAdapterConnectedSince: null,
          price: {
            id: 14,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 14,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['meeting'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 23,
          registrationPlate: 'KK-541-F',
          alias: 'Hely Citroen C1',
          resourceType: 'car',
          brand: 'Citroen',
          model: 'C1',
          color: 'grijs',
          fuelType: 'benzine',
          numberOfSeats: 4,
          location: 'Antonio Vivaldistraat',
          streetNumber: '103',
          latitude: 52.336214347229,
          longitude: 4.8844302100346,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Amsterdam',
          locktype: 'smartphone',
          parkingType: 'default',
          fuelLevel: null,
          fuelRange: null,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 600,
          chargeAdapterConnectedSince: null,
          price: {
            id: 23,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 23,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['smartphone'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 15,
          registrationPlate: 'VO-LV-01',
          alias: 'volvo-polar-micpoint-auto-accept',
          resourceType: 'car',
          brand: 'Volvo',
          model: 'Polar',
          color: null,
          fuelType: null,
          numberOfSeats: 4,
          location: 'Aakplein',
          streetNumber: null,
          latitude: 52.090793,
          longitude: 5.111107,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Utrecht',
          locktype: 'meeting',
          parkingType: 'default',
          fuelLevel: null,
          fuelRange: null,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 0,
          chargeAdapterConnectedSince: null,
          price: {
            id: 15,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 15,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['meeting'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 11,
          registrationPlate: 'AA-CD-08',
          alias: 'mywheels2-owner-resource',
          resourceType: 'car',
          brand: null,
          model: null,
          color: null,
          fuelType: null,
          numberOfSeats: 4,
          location: 'Frederik van Eedenstraat',
          streetNumber: null,
          latitude: 52.090793,
          longitude: 5.111107,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Utrecht',
          locktype: 'meeting',
          parkingType: 'default',
          fuelLevel: null,
          fuelRange: null,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 0,
          chargeAdapterConnectedSince: null,
          price: {
            id: 11,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 11,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['meeting'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 55,
          registrationPlate: 'AM-ER-01',
          alias: 'Renault ZOE Stationsplein',
          resourceType: 'Elektrische auto',
          brand: 'Renault',
          model: 'ZOE',
          color: 'wit',
          fuelType: 'elektrisch',
          numberOfSeats: 4,
          location: 'Stationsplein',
          streetNumber: '1',
          latitude: 52.15289,
          longitude: 5.374669,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Amersfoort',
          locktype: 'chipcard',
          parkingType: 'zone',
          fuelLevel: 100,
          fuelRange: 900,
          charging: false,
          chargeAdapterConnected: false,
          fuelRangeDefault: 300,
          chargeAdapterConnectedSince: null,
          price: {
            id: 55,
            hourRate: '3.50',
            kilometerRate: '0.27',
            fuelPerKilometer: '0.00',
            dayRateTotal: '35.00',
          },
          options: {
            id: 55,
            automatic: false,
            winterTires: false,
            towbar: true,
          },
          locktypes: ['chipcard'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 54,
          registrationPlate: 'EN-01-02',
          alias: 'resource-aiways-electric',
          resourceType: 'Gezinsauto',
          brand: 'Aiways',
          model: 'Aiways-model',
          color: 'Blauw',
          fuelType: 'elektrisch',
          numberOfSeats: 4,
          location: 'Stationsplein',
          streetNumber: '1',
          latitude: 52.699888,
          longitude: 5.288254,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Enkhuizen',
          locktype: 'chipcard',
          parkingType: 'default',
          fuelLevel: 100,
          fuelRange: 900,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 325,
          chargeAdapterConnectedSince: null,
          price: {
            id: 54,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 54,
            automatic: false,
            winterTires: false,
            towbar: true,
          },
          locktypes: ['chipcard'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 41,
          registrationPlate: 'XR-428-G',
          alias: 'Hely Citroen C1',
          resourceType: 'car',
          brand: 'Citroen',
          model: 'C1-5 Feel',
          color: 'blauw',
          fuelType: 'benzine',
          numberOfSeats: 4,
          location: 'Antonio Vivaldistraat',
          streetNumber: '103',
          latitude: 52.336214347229,
          longitude: 4.8844302100346,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Amsterdam',
          locktype: 'smartphone',
          parkingType: 'default',
          fuelLevel: null,
          fuelRange: null,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 600,
          chargeAdapterConnectedSince: null,
          price: {
            id: 41,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 41,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['smartphone'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 38,
          registrationPlate: 'XR-425-G',
          alias: 'Hely Citroen C1',
          resourceType: 'car',
          brand: 'Citroen',
          model: 'C1-5 Feel',
          color: 'blauw',
          fuelType: 'benzine',
          numberOfSeats: 4,
          location: 'Antonio Vivaldistraat',
          streetNumber: '103',
          latitude: 52.336214347229,
          longitude: 4.8844302100346,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Amsterdam',
          locktype: 'smartphone',
          parkingType: 'default',
          fuelLevel: null,
          fuelRange: null,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 600,
          chargeAdapterConnectedSince: null,
          price: {
            id: 38,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 38,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['smartphone'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 49,
          registrationPlate: 'GR-01-01',
          alias: 'Renault ZOE Life Kerklaan',
          resourceType: 'Elektrische auto',
          brand: 'Renault',
          model: 'ZOE Life',
          color: 'Blauw',
          fuelType: 'elektrisch',
          numberOfSeats: 4,
          location: 'Kerklaan',
          streetNumber: '1',
          latitude: 53.223938,
          longitude: 6.5511092,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Groningen',
          locktype: 'chipcard',
          parkingType: 'default',
          fuelLevel: 50,
          fuelRange: 150,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 300,
          chargeAdapterConnectedSince: null,
          price: {
            id: 49,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 49,
            automatic: true,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['chipcard'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 35,
          registrationPlate: 'XR-422-G',
          alias: 'Hely Citroen C1',
          resourceType: 'car',
          brand: 'Citroen',
          model: 'C1-5 Feel',
          color: 'blauw',
          fuelType: 'benzine',
          numberOfSeats: 4,
          location: 'Antonio Vivaldistraat',
          streetNumber: '103',
          latitude: 52.336214347229,
          longitude: 4.8844302100346,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Amsterdam',
          locktype: 'smartphone',
          parkingType: 'default',
          fuelLevel: null,
          fuelRange: null,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 600,
          chargeAdapterConnectedSince: null,
          price: {
            id: 35,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 35,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['smartphone'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 43,
          registrationPlate: 'XR-430-G',
          alias: 'Hely Citroen C1',
          resourceType: 'car',
          brand: 'Citroen',
          model: 'C1-5 Feel',
          color: 'blauw',
          fuelType: 'benzine',
          numberOfSeats: 4,
          location: 'Antonio Vivaldistraat',
          streetNumber: '103',
          latitude: 52.336214347229,
          longitude: 4.8844302100346,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Amsterdam',
          locktype: 'smartphone',
          parkingType: 'default',
          fuelLevel: null,
          fuelRange: null,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 600,
          chargeAdapterConnectedSince: null,
          price: {
            id: 43,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 43,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['smartphone'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 57,
          registrationPlate: 'KE-LL-01',
          alias: 'Renault Clio Banne Buikslootlaan',
          resourceType: 'Gezinsauto',
          brand: 'Renault',
          model: 'Clio',
          color: 'Diamond Black',
          fuelType: 'benzine',
          numberOfSeats: 4,
          location: 'Banne Buikslootlaan',
          streetNumber: '1',
          latitude: 52.4054193,
          longitude: 4.9109844,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Amsterdam',
          locktype: 'chipcard',
          parkingType: 'parking_spot',
          fuelLevel: 74,
          fuelRange: 518,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 700,
          chargeAdapterConnectedSince: null,
          price: {
            id: 57,
            hourRate: '3.50',
            kilometerRate: '0.27',
            fuelPerKilometer: '0.00',
            dayRateTotal: '35.00',
          },
          options: {
            id: 57,
            automatic: false,
            winterTires: false,
            towbar: true,
          },
          locktypes: ['chipcard'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 31,
          registrationPlate: 'XR-419-G',
          alias: 'Hely Citroen C1',
          resourceType: 'car',
          brand: 'Citroen',
          model: 'C1-5 Feel',
          color: 'blauw',
          fuelType: 'benzine',
          numberOfSeats: 4,
          location: 'Antonio Vivaldistraat',
          streetNumber: '103',
          latitude: 52.336214347229,
          longitude: 4.8844302100346,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Amsterdam',
          locktype: 'smartphone',
          parkingType: 'default',
          fuelLevel: null,
          fuelRange: null,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 600,
          chargeAdapterConnectedSince: null,
          price: {
            id: 31,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 31,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['smartphone'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 4,
          registrationPlate: 'AA-CD-99',
          alias: 'mywheels2-auto-accept-ccome',
          resourceType: 'car',
          brand: null,
          model: null,
          color: null,
          fuelType: null,
          numberOfSeats: 4,
          location: 'Leidseweg',
          streetNumber: null,
          latitude: 52.090793,
          longitude: 5.111107,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Utrecht',
          locktype: 'meeting',
          parkingType: 'default',
          fuelLevel: null,
          fuelRange: null,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 0,
          chargeAdapterConnectedSince: null,
          price: {
            id: 4,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 4,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['meeting'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 29,
          registrationPlate: 'RK-728-T',
          alias: 'Hely Citroen C4',
          resourceType: 'car',
          brand: 'Citroen',
          model: 'C4 Picasso',
          color: 'grijs',
          fuelType: 'benzine',
          numberOfSeats: 4,
          location: 'Antonio Vivaldistraat',
          streetNumber: '103',
          latitude: 52.336214347229,
          longitude: 4.8844302100346,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Amsterdam',
          locktype: 'smartphone',
          parkingType: 'default',
          fuelLevel: null,
          fuelRange: null,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 0,
          chargeAdapterConnectedSince: null,
          price: {
            id: 29,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 29,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['smartphone'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 17,
          registrationPlate: 'SK-OD-02',
          alias: 'skoda-citigo-ambition-micpoint',
          resourceType: 'car',
          brand: 'Skoda',
          model: 'Citigo',
          color: null,
          fuelType: null,
          numberOfSeats: 4,
          location: 'Keulsekade',
          streetNumber: null,
          latitude: 52.090793,
          longitude: 5.111107,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Utrecht',
          locktype: 'meeting',
          parkingType: 'default',
          fuelLevel: null,
          fuelRange: null,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 200,
          chargeAdapterConnectedSince: null,
          price: {
            id: 17,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 17,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['meeting'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 3,
          registrationPlate: 'AA-DC-88',
          alias: 'mywheels2-micpoint',
          resourceType: 'car',
          brand: null,
          model: null,
          color: null,
          fuelType: null,
          numberOfSeats: 4,
          location: 'Westplein',
          streetNumber: null,
          latitude: 52.090793,
          longitude: 5.111107,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Utrecht',
          locktype: 'meeting',
          parkingType: 'default',
          fuelLevel: null,
          fuelRange: null,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 0,
          chargeAdapterConnectedSince: null,
          price: {
            id: 3,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 3,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['meeting'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 21,
          registrationPlate: 'AA-CD-18',
          alias: 'mywheels gemeente auto',
          resourceType: 'car',
          brand: null,
          model: null,
          color: null,
          fuelType: null,
          numberOfSeats: 4,
          location: 'Walserijstraat',
          streetNumber: null,
          latitude: 52.090793,
          longitude: 5.111107,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Utrecht',
          locktype: 'meeting',
          parkingType: 'default',
          fuelLevel: null,
          fuelRange: null,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 0,
          chargeAdapterConnectedSince: null,
          price: {
            id: 21,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 21,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['meeting'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 5,
          registrationPlate: 'AA-CD-03',
          alias: 'owner wheels 3',
          resourceType: 'car',
          brand: null,
          model: null,
          color: null,
          fuelType: null,
          numberOfSeats: 4,
          location: 'Blekerstraat',
          streetNumber: null,
          latitude: 52.090793,
          longitude: 5.111107,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Utrecht',
          locktype: 'meeting',
          parkingType: 'default',
          fuelLevel: null,
          fuelRange: null,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 0,
          chargeAdapterConnectedSince: null,
          price: {
            id: 5,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 5,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['meeting'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 34,
          registrationPlate: 'XR-418-G',
          alias: 'Hely Citroen C1',
          resourceType: 'car',
          brand: 'Citroen',
          model: 'C1-5 Feel',
          color: 'blauw',
          fuelType: 'benzine',
          numberOfSeats: 4,
          location: 'Antonio Vivaldistraat',
          streetNumber: '103',
          latitude: 52.336214347229,
          longitude: 4.8844302100346,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Amsterdam',
          locktype: 'smartphone',
          parkingType: 'default',
          fuelLevel: null,
          fuelRange: null,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 600,
          chargeAdapterConnectedSince: null,
          price: {
            id: 34,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 34,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['smartphone'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 27,
          registrationPlate: 'TV-124-S',
          alias: 'Nissan Leaf Schoemakerplantage',
          resourceType: 'car',
          brand: 'Nissan',
          model: 'Leaf',
          color: 'wit',
          fuelType: 'benzine',
          numberOfSeats: 4,
          location: 'Antonio Vivaldistraat',
          streetNumber: '103',
          latitude: 52.336214347229,
          longitude: 4.8844302100346,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Amsterdam',
          locktype: 'smartphone',
          parkingType: 'default',
          fuelLevel: null,
          fuelRange: null,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 200,
          chargeAdapterConnectedSince: null,
          price: {
            id: 27,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 27,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['smartphone'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 22,
          registrationPlate: 'PB-466-H',
          alias: 'Hely Auto',
          resourceType: 'car',
          brand: 'Peugeot',
          model: '108',
          color: 'wit',
          fuelType: 'benzine',
          numberOfSeats: 4,
          location: 'Antonio Vivaldistraat',
          streetNumber: '103',
          latitude: 52.336214347229,
          longitude: 4.8844302100346,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Amsterdam',
          locktype: 'smartphone',
          parkingType: 'default',
          fuelLevel: null,
          fuelRange: null,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 250,
          chargeAdapterConnectedSince: null,
          price: {
            id: 22,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 22,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['smartphone'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 44,
          registrationPlate: 'XR-431-G',
          alias: 'Hely Citroen C1',
          resourceType: 'car',
          brand: 'Citroen',
          model: 'C1-5 Feel',
          color: 'blauw',
          fuelType: 'benzine',
          numberOfSeats: 4,
          location: 'Antonio Vivaldistraat',
          streetNumber: '103',
          latitude: 52.336214347229,
          longitude: 4.8844302100346,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Amsterdam',
          locktype: 'smartphone',
          parkingType: 'default',
          fuelLevel: null,
          fuelRange: null,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 600,
          chargeAdapterConnectedSince: null,
          price: {
            id: 44,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 44,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['smartphone'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 39,
          registrationPlate: 'XR-426-G',
          alias: 'Hely Citroen C1',
          resourceType: 'car',
          brand: 'Citroen',
          model: 'C1-5 Feel',
          color: 'blauw',
          fuelType: 'benzine',
          numberOfSeats: 4,
          location: 'Antonio Vivaldistraat',
          streetNumber: '103',
          latitude: 52.336214347229,
          longitude: 4.8844302100346,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Amsterdam',
          locktype: 'smartphone',
          parkingType: 'default',
          fuelLevel: null,
          fuelRange: null,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 600,
          chargeAdapterConnectedSince: null,
          price: {
            id: 39,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 39,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['smartphone'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 61,
          registrationPlate: 'FF-01-01',
          alias: 'Kia e-Niro Seinwachterstraat',
          resourceType: 'Gezinsauto',
          brand: 'Kia',
          model: 'e-Niro',
          color: 'Blauw',
          fuelType: 'elektrisch',
          numberOfSeats: 4,
          location: 'Seinwachterstraat',
          streetNumber: '1',
          latitude: 52.3740666,
          longitude: 4.9470408,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Amsterdam',
          locktype: 'chipcard',
          parkingType: 'parking_spot',
          fuelLevel: 100,
          fuelRange: 900,
          charging: false,
          chargeAdapterConnected: true,
          fuelRangeDefault: 0,
          chargeAdapterConnectedSince: '2023-05-08 10:35',
          price: {
            id: 61,
            hourRate: '4.25',
            kilometerRate: '0.43',
            fuelPerKilometer: '0.00',
            dayRateTotal: '42.50',
          },
          options: {
            id: 61,
            automatic: false,
            winterTires: false,
            towbar: true,
          },
          locktypes: ['chipcard'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 46,
          registrationPlate: 'XR-433-G',
          alias: 'Hely Citroen C1',
          resourceType: 'car',
          brand: 'Citroen',
          model: 'C1-5 Feel',
          color: 'blauw',
          fuelType: 'benzine',
          numberOfSeats: 4,
          location: 'Antonio Vivaldistraat',
          streetNumber: '103',
          latitude: 52.336214347229,
          longitude: 4.8844302100346,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Amsterdam',
          locktype: 'smartphone',
          parkingType: 'default',
          fuelLevel: null,
          fuelRange: null,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 600,
          chargeAdapterConnectedSince: null,
          price: {
            id: 46,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 46,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['smartphone'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 2,
          registrationPlate: 'AA-CD-09',
          alias: 'mywheels2-auto-accept',
          resourceType: 'car',
          brand: null,
          model: null,
          color: null,
          fuelType: null,
          numberOfSeats: 4,
          location: 'Croeselaan',
          streetNumber: null,
          latitude: 52.090793,
          longitude: 5.111107,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Utrecht',
          locktype: 'meeting',
          parkingType: 'default',
          fuelLevel: null,
          fuelRange: null,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 0,
          chargeAdapterConnectedSince: null,
          price: {
            id: 2,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 2,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['meeting'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 33,
          registrationPlate: 'XR-417-G',
          alias: 'Hely Citroen C1',
          resourceType: 'car',
          brand: 'Citroen',
          model: 'C1-5 Feel',
          color: 'grijs',
          fuelType: 'benzine',
          numberOfSeats: 4,
          location: 'Antonio Vivaldistraat',
          streetNumber: '103',
          latitude: 52.336214347229,
          longitude: 4.8844302100346,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Amsterdam',
          locktype: 'smartphone',
          parkingType: 'default',
          fuelLevel: null,
          fuelRange: null,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 600,
          chargeAdapterConnectedSince: null,
          price: {
            id: 33,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 33,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['smartphone'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 58,
          registrationPlate: 'TE-ST-01',
          alias: 'Kia e-Niro KNSM Eiland (test)',
          resourceType: 'Elektrische auto',
          brand: 'Kia',
          model: 'e-Niro',
          color: 'wit',
          fuelType: 'elektrisch',
          numberOfSeats: 4,
          location: 'KNSM Eiland (test)',
          streetNumber: '1',
          latitude: 52.377205,
          longitude: 4.945727,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Amsterdam',
          locktype: 'chipcard',
          parkingType: 'zone',
          fuelLevel: 100,
          fuelRange: 400,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 400,
          chargeAdapterConnectedSince: null,
          price: {
            id: 58,
            hourRate: '4.25',
            kilometerRate: '0.36',
            fuelPerKilometer: '0.00',
            dayRateTotal: '42.50',
          },
          options: { id: 58, automatic: true, winterTires: true, towbar: true },
          locktypes: ['chipcard'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 50,
          registrationPlate: 'GR-01-02',
          alias: 'Renault ZOE Zen Westersingel',
          resourceType: 'Elektrische auto',
          brand: 'Renault',
          model: 'ZOE Zen',
          color: 'Groen',
          fuelType: 'elektrisch',
          numberOfSeats: 4,
          location: 'Westersingel',
          streetNumber: '1',
          latitude: 53.216873,
          longitude: 6.557184,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Groningen',
          locktype: 'chipcard',
          parkingType: 'default',
          fuelLevel: 75,
          fuelRange: 225,
          charging: true,
          chargeAdapterConnected: null,
          fuelRangeDefault: 300,
          chargeAdapterConnectedSince: null,
          price: {
            id: 50,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 50,
            automatic: false,
            winterTires: true,
            towbar: false,
          },
          locktypes: ['chipcard'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 36,
          registrationPlate: 'XR-423-G',
          alias: 'Hely Citroen C1',
          resourceType: 'car',
          brand: 'Citroen',
          model: 'C1-5 Feel',
          color: 'blauw',
          fuelType: 'benzine',
          numberOfSeats: 4,
          location: 'Antonio Vivaldistraat',
          streetNumber: '103',
          latitude: 52.336214347229,
          longitude: 4.8844302100346,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Amsterdam',
          locktype: 'smartphone',
          parkingType: 'default',
          fuelLevel: null,
          fuelRange: null,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 600,
          chargeAdapterConnectedSince: null,
          price: {
            id: 36,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 36,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['smartphone'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
      {
        resource: {
          id: 42,
          registrationPlate: 'XR-429-G',
          alias: 'Hely Citroen C1',
          resourceType: 'car',
          brand: 'Citroen',
          model: 'C1-5 Feel',
          color: 'blauw',
          fuelType: 'benzine',
          numberOfSeats: 4,
          location: 'Antonio Vivaldistraat',
          streetNumber: '103',
          latitude: 52.336214347229,
          longitude: 4.8844302100346,
          advertisement: null,
          created: '2023-05-09 16:35',
          city: 'Amsterdam',
          locktype: 'smartphone',
          parkingType: 'default',
          fuelLevel: null,
          fuelRange: null,
          charging: false,
          chargeAdapterConnected: null,
          fuelRangeDefault: 600,
          chargeAdapterConnectedSince: null,
          price: {
            id: 42,
            hourRate: '3.25',
            kilometerRate: '0.30',
            fuelPerKilometer: '0.13',
            dayRateTotal: '32.50',
          },
          options: {
            id: 42,
            automatic: false,
            winterTires: false,
            towbar: false,
          },
          locktypes: ['smartphone'],
          favorite: false,
          rating_totals: null,
        },
        availability: null,
        shouldDischarge: false,
        distance: null,
      },
    ],
    current: 57,
    offset: 0,
    limit: 57,
    total: 57,
  },
  id: 0,
}
